### ISSUE TITLE
createFromDir error

### ISSUE THREAD

**Issue by mazondo** [BitBalloon/grunt-bitballoon#1]
Getting the following error when running:

```
Fatal error: createFromDir is not defined
```

devDependencies:

```
"grunt": "^0.4.5",
    "grunt-bitballoon": "^0.1.3",
    "grunt-connect-rewrite": "^0.2.1",
    "grunt-contrib-connect": "^0.10.1",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-express": "^1.4.1",
    "grunt-parallel": "^0.4.1",
    "grunt-shell": "^1.1.2"
```

**Comment by rylanb** [comment]
I am also getting this error when trying to deploy. Fully blocks ability to deploy and is an error in 

grunt-bitballoon/node_modules/bitballoon/lib/site.js Line 183: 

```
createFromDir(this.client, attributes.dir, this.id, cb);
```

No changes if updated to:

```
Site.createFromDir(this.client, attributes.dir, this.id, cb);
error: "Fatal error: string is not a function"
```

nor: 

```
this.createFromDir(this.client, attributes.dir, this.id, cb);
error: "Fatal error: undefined is not a function"
```

One of the last two might indicate an issue with my setup, but the documentation is thin around this.

**Comment by mazondo** [comment]
I was thinking about diving into this today or tomorrow to see if I could figure it out.  Thanks for the note on what you tried

**Comment by biilmann** [comment]
Had a look at it, and seems to be a bug introduced when we changed the recommended way to work with our REST API a while back, to make working with individual deploys more explicit and make sure running two concurrent deploys wouldn't cause trouble.

I've pushed a quick fix to the bitballoon npm package and updated it to 0.2.2, please test it out and see if this solves your problem...

**Comment by mazondo** [comment]
@biilmann worked great.  thanks
